### ISSUE TITLE
Rust CLI for `scan.py`

### ISSUE THREAD

**Issue by cdstanford** [PLSysSec/cargo-scan#10]
Since a bunch of functionality is duplicated in `scan.py` and `rst-src/src/effect.rs`, it may be worth moving the CLI to Rust. It would be nice at least to have the basic CLI working: modify the file
`rust-src/src/main.rs` using `clap` to generate a basic CLI matching the main options of `scan.py` (see the bottom of `scan.py`: all the argparse code.)
The MIRAI options can be ignored for now.

**Comment by bholley** [comment]
Given that our eventual goal is to integrate this into cargo-vet, having the logic be in Rust would have the side-benefit of facilitating that potential future integration.

Note that cargo-vet has its own rather extensive CLI and infrastructure for downloading crates, so I wouldn't invest too much energy in those parts, and ideally we'd structure the Rust code so that the core logic could be used as a library without those things.

**Comment by cdstanford** [comment]
this is happening somewhat incrementally, as certain features get implemented on the Rust side. Currently, I'm not planning to move the experiment scripting stuff over right away -- since that's more convenient to write and modify in Python anyway.

**Comment by cdstanford** [comment]
We will likely switch to @DavidThien's frontend for the user-facing entrypoint soon.
